name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: fmt, clippy

    - name: Run cargo fmt (Check formatting)
      run: cargo fmt -- --check

    - name: Run cargo clippy (Linting)
      run: cargo clippy -- -D warnings

    - name: Run cargo test (Testing)
      run: cargo test --all
