name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      WORKING_DIR: minigrep

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: clippy

    - name: Check
      run: cargo check
      working-directory: ${{ env.WORKING_DIR }}

    - name: Format
      run: cargo fmt -- --check
      working-directory: ${{ env.WORKING_DIR }}

    - name: Test
      run: cargo test
      working-directory: ${{ env.WORKING_DIR }}

    - name: Release
      run: cargo build --release
      working-directory: ${{ env.WORKING_DIR }}